---
- name: Update Group1
  hosts: all
  become: yes

  tasks:
  - name: Ensure HTTPD installed
    package:
      name: httpd
      state: present
    when: ansible_distribution == "CentOS"

  - name: Ensure HTTPD started
    service:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"

  - name: Ensure HTTPD Enabled
    service:
      name: httpd
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: Ensure apt updated
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Ensure Apache2 Installed
    package:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Ensure Apache2 started
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"

  - name: Ensure Apache2 Enabled
    service:
      name: apache2
      enabled: yes
    when: ansible_distribution == "Ubuntu"

...
